### ISSUE TITLE
数据集下载缺失

### ISSUE THREAD

**Issue by 1129571** [MRzzm/HDTF#17]
根据作者提供的项目，我从[https://github.com/universome/HDTF](url)下载数据集，但是下载下来的视频只有157个，这是正常的吗？

**Comment by vinjancai** [comment]
报错一个文件都下载不下来

C:\Users\ASUS\anaconda3\python.exe D:/02_github_model/HDTF-main/download.py --output_dir ./output/ --num_workers 8
Clip RD/Radio6_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire RD/Radio6 does not contain any crops, hence is broken. Discarding it.
Clip RD/Radio15_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire RD/Radio15 does not contain any crops, hence is broken. Discarding it.
Entire RD/Radio24 does not contain any clip intervals, hence is broken. Discarding it.
Entire WDA/锘緾arolynMaloney2 does not contain any clip intervals, hence is broken. Discarding it.
Clip WDA/DeanPhillips_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WDA/DeanPhillips does not contain any crops, hence is broken. Discarding it.
Clip WDA/JimMcGovern1_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WDA/JimMcGovern1 does not contain any crops, hence is broken. Discarding it.
Clip WDA/JimMcGovern_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WDA/JimMcGovern does not contain any crops, hence is broken. Discarding it.
Clip WDA/JeffMerkley0_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WDA/JeffMerkley0 does not contain any crops, hence is broken. Discarding it.
Clip WDA/LindaSnchez_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WDA/LindaSnchez does not contain any crops, hence is broken. Discarding it.
Clip WDA/ByronDorgan0_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WDA/ByronDorgan0 does not contain any crops, hence is broken. Discarding it.
Clip WRA/BillCassidy_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WRA/BillCassidy does not contain any crops, hence is broken. Discarding it.
Clip WRA/MittRomney_1.mp4 is not present in crops, hence is broken. Discarding it.
Clip WRA/RudyGiuliani_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WRA/RudyGiuliani does not contain any crops, hence is broken. Discarding it.
Clip WRA/JaimeHerreraBeutler_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WRA/JaimeHerreraBeutler does not contain any crops, hence is broken. Discarding it.
Clip WRA/DuncanHunter_1.mp4 is not present in crops, hence is broken. Discarding it.
Clip WRA/KevinBrady0_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WRA/KevinBrady0 does not contain any crops, hence is broken. Discarding it.
Clip WRA/CandiceMiller_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire WRA/CandiceMiller does not contain any crops, hence is broken. Discarding it.
Downloading videos into ./output/ (note: without sound):   0%|          | 0/355 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\02_github_model\HDTF-main\download.py", line 105, in task_proxy
    return download_and_process_video(**kwargs)
  File "D:\02_github_model\HDTF-main\download.py", line 114, in download_and_process_video
    download_result = download_video(video_data['id'], raw_download_path, resolution=video_data['resolution'], log_file=raw_download_log_file)
  File "D:\02_github_model\HDTF-main\download.py", line 177, in download_video
    return_code = subprocess.call(command, stderr=stderr)
  File "C:\Users\ASUS\anaconda3\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\ASUS\anaconda3\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ASUS\anaconda3\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/02_github_model/HDTF-main/download.py", line 238, in <module>
    download_hdtf(
  File "D:/02_github_model/HDTF-main/download.py", line 44, in download_hdtf
    for _ in tqdm(pool.imap_unordered(task_proxy, task_kwargs), **tqdm_kwargs):
  File "C:\Users\ASUS\anaconda3\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\ASUS\anaconda3\lib\multiprocessing\pool.py", line 868, in next
    raise value
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Process finished with exit code 1

**Comment by 1129571** [comment]
> 报错一个文件都下载不下来
> 
> C:\Users\ASUS\anaconda3\python.exe D:/02_github_model/HDTF-main/download.py --output_dir ./output/ --num_workers 8 Clip RD/Radio6_0.mp4 is not present in crops, hence is broken. Discarding it. Entire RD/Radio6 does not contain any crops, hence is broken. Discarding it. Clip RD/Radio15_0.mp4 is not present in crops, hence is broken. Discarding it. Entire RD/Radio15 does not contain any crops, hence is broken. Discarding it. Entire RD/Radio24 does not contain any clip intervals, hence is broken. Discarding it. Entire WDA/锘緾arolynMaloney2 does not contain any clip intervals, hence is broken. Discarding it. Clip WDA/DeanPhillips_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WDA/DeanPhillips does not contain any crops, hence is broken. Discarding it. Clip WDA/JimMcGovern1_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WDA/JimMcGovern1 does not contain any crops, hence is broken. Discarding it. Clip WDA/JimMcGovern_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WDA/JimMcGovern does not contain any crops, hence is broken. Discarding it. Clip WDA/JeffMerkley0_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WDA/JeffMerkley0 does not contain any crops, hence is broken. Discarding it. Clip WDA/LindaSnchez_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WDA/LindaSnchez does not contain any crops, hence is broken. Discarding it. Clip WDA/ByronDorgan0_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WDA/ByronDorgan0 does not contain any crops, hence is broken. Discarding it. Clip WRA/BillCassidy_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WRA/BillCassidy does not contain any crops, hence is broken. Discarding it. Clip WRA/MittRomney_1.mp4 is not present in crops, hence is broken. Discarding it. Clip WRA/RudyGiuliani_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WRA/RudyGiuliani does not contain any crops, hence is broken. Discarding it. Clip WRA/JaimeHerreraBeutler_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WRA/JaimeHerreraBeutler does not contain any crops, hence is broken. Discarding it. Clip WRA/DuncanHunter_1.mp4 is not present in crops, hence is broken. Discarding it. Clip WRA/KevinBrady0_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WRA/KevinBrady0 does not contain any crops, hence is broken. Discarding it. Clip WRA/CandiceMiller_0.mp4 is not present in crops, hence is broken. Discarding it. Entire WRA/CandiceMiller does not contain any crops, hence is broken. Discarding it. Downloading videos into ./output/ (note: without sound): 0%| | 0/355 [00:00<?, ?it/s] multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "C:\Users\ASUS\anaconda3\lib\multiprocessing\pool.py", line 125, in worker result = (True, func(*args, **kwds)) File "D:\02_github_model\HDTF-main\download.py", line 105, in task_proxy return download_and_process_video(**kwargs) File "D:\02_github_model\HDTF-main\download.py", line 114, in download_and_process_video download_result = download_video(video_data['id'], raw_download_path, resolution=video_data['resolution'], log_file=raw_download_log_file) File "D:\02_github_model\HDTF-main\download.py", line 177, in download_video return_code = subprocess.call(command, stderr=stderr) File "C:\Users\ASUS\anaconda3\lib\subprocess.py", line 340, in call with Popen(*popenargs, **kwargs) as p: File "C:\Users\ASUS\anaconda3\lib\subprocess.py", line 858, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\ASUS\anaconda3\lib\subprocess.py", line 1311, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系统找不到指定的文件。 """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:/02_github_model/HDTF-main/download.py", line 238, in download_hdtf( File "D:/02_github_model/HDTF-main/download.py", line 44, in download_hdtf for _ in tqdm(pool.imap_unordered(task_proxy, task_kwargs), **tqdm_kwargs): File "C:\Users\ASUS\anaconda3\lib\site-packages\tqdm\std.py", line 1178, in **iter** for obj in iterable: File "C:\Users\ASUS\anaconda3\lib\multiprocessing\pool.py", line 868, in next raise value FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> 
> Process finished with exit code 1

你这可能是环境没配好，youtube-dl出问题的可能性比较大，我刚刚试了下还可以正常下载。

1. 试试更新一下youtube-dl：https://github.com/ytdl-org/youtube-dl/tree/master 因为youtube经常更新，yt-dl只在github更新。下载最新的覆盖pythonPath\Lib\site-packages。
2. 另外，国内下载记得看看是不是梯子的问题。

可以试试youtube-dl能不能下载哔哩哔哩的视频，看看是不是youtube-dl的问题。然后再看看youtube-dl能不能下载youtube视频，就知道是不是梯子的问题了

**Comment by kiritosaac** [comment]
> > 报错一个文件都下载不下来
> > C：\Users\ASUS\anaconda3\python.exe D：/02_github_model/HDTF-main/download.py --output_dir ./output/ --num_workers 8 Clip RD/Radio6_0.mp4 不存在于农作物中，因此已损坏。丢弃它。整个 RD/Radio6 不包含任何农作物，因此已损坏。丢弃它。Clip RD/Radio15_0.mp4 不存在于作物中，因此已损坏。丢弃它。整个 RD/Radio15 不包含任何农作物，因此已损坏。丢弃它。整个 RD/Radio24 不包含任何剪辑间隔，因此已损坏。丢弃它。整个 WDA/锘緾arolynMaloney2 不包含任何剪辑间隔，因此已损坏。丢弃它。Clip WDA/DeanPhillips_0.mp4 在作物中不存在，因此已损坏。丢弃它。整个 WDA/DeanPhillips 不包含任何农作物，因此被打破了。丢弃它。Clip WDA/JimMcGovern1_0.mp4 在农作物中不存在，因此已损坏。丢弃它。整个 WDA/JimMcGovern1 不包含任何作物，因此已损坏。丢弃它。Clip WDA/JimMcGovern_0.mp4 不存在于农作物中，因此已损坏。丢弃它。整个 WDA/JimMcGovern 不包含任何农作物，因此被破坏。丢弃它。Clip WDA/JeffMerkley0_0.mp4 不存在于作物中，因此已损坏。丢弃它。整个 WDA/JeffMerkley0 不包含任何农作物，因此已损坏。丢弃它。Clip WDA/LindaSnchez_0.mp4 不存在于农作物中，因此已损坏。丢弃它。整个 WDA/LindaSnchez 不包含任何农作物，因此被破坏。丢弃它。Clip WDA/ByronDorgan0_0.mp4 在作物中不存在，因此已损坏。丢弃它。整个 WDA/ByronDorgan0 不包含任何农作物，因此被破坏。丢弃它。夹子 WRA/BillCassidy_0.mp4 在农作物中不存在，因此已损坏。丢弃它。整个 WRA/BillCassidy 不包含任何农作物，因此被破坏。丢弃它。夹子 WRA/MittRomney_1.mp4 不存在于农作物中，因此已损坏。丢弃它。Clip WRA/RudyGiuliani_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个 WRA/RudyGiuliani 不含任何农作物，因此被打破。丢弃它。Clip WRA/JaimeHerreraBeutler_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个WRA/JaimeHerreraBeutler不包含任何农作物，因此被打破了。丢弃它。夹子 WRA/DuncanHunter_1.mp4 不存在于农作物中，因此被破坏。丢弃它。夹子 WRA/KevinBrady0_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个 WRA/KevinBrady0 不包含任何农作物，因此被破坏。丢弃它。Clip WRA/CandiceMiller_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个 WRA/CandiceMiller 不包含任何农作物，因此已损坏。丢弃它。将视频下载到 ./output/ 中（注意：没有声音）：0%| |0/355 [00：00<?, ?it/s] multiprocessing.pool.RemoteTraceback： “”“ 回溯（最近一次调用最后一次）： 文件”C：\Users\ASUS\anaconda3\lib\multiprocessing\pool.py“，第 125 行，在 worker result = （True， func（*args， **kwds）） 文件”D：\02_github_model\HDTF-main\download.py“，第 105 行，在task_proxy返回download_and_process_video （**kwargs） 文件”D：\02_github_model\HDTF-main\download.py“，第 114 行，在 download_and_process_video download_result = download_video（video_data['id']， raw_download_path， resolution=video_data['resolution']， log_file=raw_download_log_file） 文件“D：\02_github_model\HDTF-main\download.py”，第 177 行，download_video return_code = subprocess.call（command， stderr=stderr） 文件“C：\Users\ASUS\anaconda3\lib\subprocess.py”，第 340 行，调用 Popen（*popenargs， **kwargs） as p： 文件“C：\Users\ASUS\anaconda3\lib\subprocess.py”，第 858 行， 在 **init** self._execute_child（args， executable， preexec_fn， close_fds， File “C：\Users\ASUS\anaconda3\lib\subprocess.py”， line 1311， in _execute_child hp， ht， pid， tid = _winapi.CreateProcess（executable， args， FileNotFoundError： [WinError 2] 系统找不到指定的文件。"""
> > 上述异常是导致以下异常的直接原因：
> > 回溯（最近一次调用最后一次）： 文件“D：/02_github_model/HDTF-main/download.py”，第 238 行，在 download_hdtf（ 文件“D：/02_github_model/HDTF-main/download.py”，第 44 行，在 tqdm（pool.imap_unordered（task_proxy， task_kwargs）， **tqdm_kwargs） 中的 _ download_hdtf中：文件 “C：\Users\ASUS\anaconda3\lib\site-packages\tqdm\std.py”，第 1178 行，**在 iter** 中for obj in iterable： File “C：\Users\ASUS\anaconda3\lib\multiprocessing\pool.py”， line 868， in next raise value FileNotFoundError： [WinError 2] 系统找不到指定的文件。
> > 进程已完成，退出代码为 1
> 
> 你这可能是环境没配好，youtube-dl出问题的可能性比较大，我刚刚试了下还可以正常下载。
> 
> 1. 试试更新一下youtube-dl：https://github.com/ytdl-org/youtube-dl/tree/master 因为youtube经常更新，yt-dl只在github更新。下载最新的覆盖pythonPath\Lib\site-packages。
> 2. 另外，国内下载记得看看是不是梯子的问题。
> 
> 可以试试youtube-dl能不能下载哔哩哔哩的视频，看看是不是youtube-dl的问题。然后再看看youtube-dl能不能下载youtube视频，就知道是不是梯子的问题了

我这个能下载倒是能下载，我是用的yt-dlp下载的，但是也出现了类似
Clip RD/Radio6_0.mp4 is not present in crops, hence is broken. Discarding it.
Entire RD/Radio6 does not contain any crops, hence is broken. Discarding it.
上面的情况。这个要怎么解决呢

**Comment by 1129571** [comment]
> > > 报错一个文件都下载不下来
> > > C：\Users\ASUS\anaconda3\python.exe D：/02_github_model/HDTF-main/download.py --output_dir ./output/ --num_workers 8 Clip RD/Radio6_0.mp4 不存在于农作物中，因此已损坏。丢弃它。整个 RD/Radio6 不包含任何农作物，因此已损坏。丢弃它。Clip RD/Radio15_0.mp4 不存在于作物中，因此已损坏。丢弃它。整个 RD/Radio15 不包含任何农作物，因此已损坏。丢弃它。整个 RD/Radio24 不包含任何剪辑间隔，因此已损坏。丢弃它。整个 WDA/锘緾arolynMaloney2 不包含任何剪辑间隔，因此已损坏。丢弃它。Clip WDA/DeanPhillips_0.mp4 在作物中不存在，因此已损坏。丢弃它。整个 WDA/DeanPhillips 不包含任何农作物，因此被打破了。丢弃它。Clip WDA/JimMcGovern1_0.mp4 在农作物中不存在，因此已损坏。丢弃它。整个 WDA/JimMcGovern1 不包含任何作物，因此已损坏。丢弃它。Clip WDA/JimMcGovern_0.mp4 不存在于农作物中，因此已损坏。丢弃它。整个 WDA/JimMcGovern 不包含任何农作物，因此被破坏。丢弃它。Clip WDA/JeffMerkley0_0.mp4 不存在于作物中，因此已损坏。丢弃它。整个 WDA/JeffMerkley0 不包含任何农作物，因此已损坏。丢弃它。Clip WDA/LindaSnchez_0.mp4 不存在于农作物中，因此已损坏。丢弃它。整个 WDA/LindaSnchez 不包含任何农作物，因此被破坏。丢弃它。Clip WDA/ByronDorgan0_0.mp4 在作物中不存在，因此已损坏。丢弃它。整个 WDA/ByronDorgan0 不包含任何农作物，因此被破坏。丢弃它。夹子 WRA/BillCassidy_0.mp4 在农作物中不存在，因此已损坏。丢弃它。整个 WRA/BillCassidy 不包含任何农作物，因此被破坏。丢弃它。夹子 WRA/MittRomney_1.mp4 不存在于农作物中，因此已损坏。丢弃它。Clip WRA/RudyGiuliani_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个 WRA/RudyGiuliani 不含任何农作物，因此被打破。丢弃它。Clip WRA/JaimeHerreraBeutler_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个WRA/JaimeHerreraBeutler不包含任何农作物，因此被打破了。丢弃它。夹子 WRA/DuncanHunter_1.mp4 不存在于农作物中，因此被破坏。丢弃它。夹子 WRA/KevinBrady0_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个 WRA/KevinBrady0 不包含任何农作物，因此被破坏。丢弃它。Clip WRA/CandiceMiller_0.mp4 不存在于农作物中，因此被破坏。丢弃它。整个 WRA/CandiceMiller 不包含任何农作物，因此已损坏。丢弃它。将视频下载到 ./output/ 中（注意：没有声音）：0%| |0/355 [00：00<?, ?it/s] multiprocessing.pool.RemoteTraceback： “”“ 回溯（最近一次调用最后一次）： 文件”C：\Users\ASUS\anaconda3\lib\multiprocessing\pool.py“，第 125 行，在 worker result = （True， func（*args， **kwds）） 文件”D：\02_github_model\HDTF-main\download.py“，第 105 行，在task_proxy返回download_and_process_video （**kwargs） 文件”D：\02_github_model\HDTF-main\download.py“，第 114 行，在 download_and_process_video download_result = download_video（video_data['id']， raw_download_path， resolution=video_data['resolution']， log_file=raw_download_log_file） 文件“D：\02_github_model\HDTF-main\download.py”，第 177 行，download_video return_code = subprocess.call（command， stderr=stderr） 文件“C：\Users\ASUS\anaconda3\lib\subprocess.py”，第 340 行，调用 Popen（*popenargs， **kwargs） as p： 文件“C：\Users\ASUS\anaconda3\lib\subprocess.py”，第 858 行， 在 **init** self._execute_child（args， executable， preexec_fn， close_fds， File “C：\Users\ASUS\anaconda3\lib\subprocess.py”， line 1311， in _execute_child hp， ht， pid， tid = _winapi.CreateProcess（executable， args， FileNotFoundError： [WinError 2] 系统找不到指定的文件。"""
> > > 上述异常是导致以下异常的直接原因：
> > > 回溯（最近一次调用最后一次）： 文件“D：/02_github_model/HDTF-main/download.py”，第 238 行，在 download_hdtf（ 文件“D：/02_github_model/HDTF-main/download.py”，第 44 行，在 tqdm（pool.imap_unordered（task_proxy， task_kwargs）， **tqdm_kwargs） 中的 _ download_hdtf中：文件 “C：\Users\ASUS\anaconda3\lib\site-packages\tqdm\std.py”，第 1178 行，**在 iter** 中for obj in iterable： File “C：\Users\ASUS\anaconda3\lib\multiprocessing\pool.py”， line 868， in next raise value FileNotFoundError： [WinError 2] 系统找不到指定的文件。
> > > 进程已完成，退出代码为 1
> > 
> > 
> > 你这可能是环境没配好，youtube-dl出问题的可能性比较大，我刚刚试了下还可以正常下载。
> > 
> > 1. 试试更新一下youtube-dl：https://github.com/ytdl-org/youtube-dl/tree/master 因为youtube经常更新，yt-dl只在github更新。下载最新的覆盖pythonPath\Lib\site-packages。
> > 2. 另外，国内下载记得看看是不是梯子的问题。
> > 
> > 可以试试youtube-dl能不能下载哔哩哔哩的视频，看看是不是youtube-dl的问题。然后再看看youtube-dl能不能下载youtube视频，就知道是不是梯子的问题了
> 
> 我这个能下载倒是能下载，我是用的yt-dlp下载的，但是也出现了类似 Clip RD/Radio6_0.mp4 is not present in crops, hence is broken. Discarding it. Entire RD/Radio6 does not contain any crops, hence is broken. Discarding it. 上面的情况。这个要怎么解决呢

我也有这个问题，只能下载一部分，所以才提这个issue的

**Comment by 1129571** [comment]
我发现在XX_resolution.txt中，所有1080p的视频都下载失败了，不知道是不是youtube-dl的问题，我的解决办法是把1080都改成720

**Comment by 1129571** [comment]
我发现在XX_resolution.txt中，所有1080p的视频都下载失败了，不知道是不是youtube-dl的问题，我的解决办法是把1080都改成720

**Comment by 1129571** [comment]
或者使用这个命令也可以
 command = [
        "youtube-dl",
        "https://youtube.com/watch?v={}".format(video_id), "--quiet",
        # "-f", video_selection,
        "--output", download_path,
        "--no-continue"
    ]
